const data = [
  { label: "Adventurer", value: "adventurer", url: "https://api.dicebear.com/9.x/adventurer/svg" },
  { label: "Adventurer Neutral", value: "adventurer-neutral", url: "https://api.dicebear.com/9.x/adventurer-neutral/svg" },
  { label: "Avataaars", value: "avataaars", url: "https://api.dicebear.com/9.x/avataaars/svg" },
  { label: "Avataaars Neutral", value: "avataaars-neutral", url: "https://api.dicebear.com/9.x/avataaars-neutral/svg" },
  { label: "Big Ears", value: "big-ears", url: "https://api.dicebear.com/9.x/big-ears/svg" },
  { label: "Big Ears Neutral", value: "big-ears-neutral", url: "https://api.dicebear.com/9.x/big-ears-neutral/svg" },
  { label: "Big Smile", value: "big-smile", url: "https://api.dicebear.com/9.x/big-smile/svg" },
  { label: "Bottts", value: "bottts", url: "https://api.dicebear.com/9.x/bottts/svg" },
  { label: "Bottts Neutral", value: "bottts-neutral", url: "https://api.dicebear.com/9.x/bottts-neutral/svg" },
  { label: "Croodles", value: "croodles", url: "https://api.dicebear.com/9.x/croodles/svg" },
  { label: "Croodles Neutral", value: "croodles-neutral", url: "https://api.dicebear.com/9.x/croodles-neutral/svg" },
  { label: "Dylan", value: "dylan", url: "https://api.dicebear.com/9.x/dylan/svg" },
  { label: "Fun Emoji", value: "fun-emoji", url: "https://api.dicebear.com/9.x/fun-emoji/svg" },
  { label: "Lorelei", value: "lorelei", url: "https://api.dicebear.com/9.x/lorelei/svg" },
  { label: "Lorelei Neutral", value: "lorelei-neutral", url: "https://api.dicebear.com/9.x/lorelei-neutral/svg" },
  { label: "Micah", value: "micah", url: "https://api.dicebear.com/9.x/micah/svg" },
  { label: "Miniavs", value: "miniavs", url: "https://api.dicebear.com/9.x/miniavs/svg" },
  { label: "Notionists", value: "notionists", url: "https://api.dicebear.com/9.x/notionists/svg" },
  { label: "Notionists Neutral", value: "notionists-neutral", url: "https://api.dicebear.com/9.x/notionists-neutral/svg" },
  { label: "Open Peeps", value: "open-peeps", url: "https://api.dicebear.com/9.x/open-peeps/svg" },
  { label: "Personas", value: "personas", url: "https://api.dicebear.com/9.x/personas/svg" },
  { label: "Toon Head", value: "toon-head", url: "https://api.dicebear.com/9.x/toon-head/svg" },

  { label: "Glass", value: "glass", url: "https://api.dicebear.com/9.x/glass/svg" },
  { label: "Icons", value: "icons", url: "https://api.dicebear.com/9.x/icons/svg" },
  { label: "Identicon", value: "identicon", url: "https://api.dicebear.com/9.x/identicon/svg" },
  { label: "Initials", value: "initials", url: "https://api.dicebear.com/9.x/initials/svg" },
  { label: "Pixel Art", value: "pixel-art", url: "https://api.dicebear.com/9.x/pixel-art/svg" },
  { label: "Pixel Art Neutral", value: "pixel-art-neutral", url: "https://api.dicebear.com/9.x/pixel-art-neutral/svg" },
  { label: "Rings", value: "rings", url: "https://api.dicebear.com/9.x/rings/svg" },
  { label: "Shapes", value: "shapes", url: "https://api.dicebear.com/9.x/shapes/svg" },
  { label: "Thumbs", value: "thumbs", url: "https://api.dicebear.com/9.x/thumbs/svg" }
];

export default data